
name: Deploy

on:
  push:
    branches:
      - main


jobs:
  # Build job
  # build:

  # Deploy job
  deploy:
    # Deploy to the github-pages environment
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: add config
        run: echo "${{ secrets.CONFIG }}" > config.js

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
